spring:
  application:
    name: GAMES-AGGREGATOR

server:
  port: ${SERVER_PORT:8085}

eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}