spring:
  application:
    name: REGISTRY-SERVER

server:
  port: ${SERVER_PORT:8761}
  
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}